### ISSUE TITLE
[CIFAR10_part1]Bug in function of AddCheckpoints?

### ISSUE THREAD

**Issue by PeizeSun** [caffe2/tutorials#10]
def AddCheckpoints(model, checkpoint_iters, db_type):
    ITER = brew.iter(train_model, "iter")
    train_model.Checkpoint([ITER] + train_model.params, [], db=os.path.join(unique_timestamp, "cifar10_checkpoint_%05d.lmdb"), db_type="lmdb", every=checkpoint_iters)

I guess all "train_model" inside AddCheckpoints should be "model", in terms of consistent name.
Is this a bug or I misunderstand something?

**Comment by TheMaikXX** [comment]
I suppose there really should be just a 'model' in my opinion...

**Comment by orionr** [comment]
Good catch! Looks like AddCheckpoints is only ever called with train_model so it is functional as-is, but you're right that it should be model inside the function. @PeizeSun  or @TheMaikXX do you want to submit a PR with a fix? If not, we'll take care of it. Thanks.

**Comment by orionr** [comment]
Fixed by https://github.com/caffe2/tutorials/pull/18
