### ISSUE TITLE
new caffe2::Predictor crash

### ISSUE THREAD

**Issue by cswwp** [caffe2/tutorials#15]
I have converted shufflenet from pytorch to caffe pb model, and i test it on pc is ok, but it crash when use new caffe2::Predictor crash run on the mobile, anyone help me ?

**Comment by orionr** [comment]
Hi @cswwp - can you get more details on the crash itself? Does it say anything about operator not available or something? Also, maybe verify that you can run https://github.com/caffe2/AICamera first
