### ISSUE TITLE
No ImageInput in ModelHelper

### ISSUE THREAD

**Issue by zieitokk** [caffe2/tutorials#19]
Hi,

I was running the `Multi-GPU_Training.ipynb` tutorial file. As I process the file to Part 8, it said that 

> Method ImageInput is not a registered operator. Did you mean: []. 

So I checked the function **ImageInput** and find out that there is no such function in **ModelHelper** and thus may caused the problem.

So where should I do to load images in order to get through the `Multi-GPU_Training.ipynb` tutorial?

Thank you.

**Comment by orionr** [comment]
Hi @zieitokk. Unfortunately, with our merging of Caffe2 and PyTorch in PyTorch 1.0 we don't by default include operators and code that depends on OpenCV or ffmpeg libraries so we can limit the dependencies (and issues with installs) for most users. What this means, though, is that to go through the tutorial you'll now need to build from source. You can do this with

```
git clone --recursive https://github.com/pytorch/pytorch && cd pytorch
USE_OPENCV=1 USE_FFMPEG=1 python setup.py install
```

Let us know if you have issues.
