### ISSUE TITLE
How to install Caffe2 on Windows?

### ISSUE THREAD

**Issue by sarimmehdi** [caffe2/tutorials#25]
Hello. caffe2 installation is a mess. The official tutorial is obviously not correct so I had to follow this one: http://gianni.rosagallina.com/en/posts/2018/10/04/caffe2-gpu-windows-1.html

However, here the author says, during Step 2, to change some settings for cmake???? Are these settings supposed to be applied in build_windows.bat or am I supposed to write 
 -DTORCH_CUDA_ARCH_LIST=6.1 in some other file? Please explain to me how to do this. If possible, share a working build_windows,bat file

**Comment by orionr** [comment]
@sarimmehdi, Caffe2 installation separate from PyTorch is no longer supported. You can install one of the previous binary installs, but I'd recommend installing PyTorch for Windows and you should have the  Caffe2 APIs also available to you, although not officially supported. If you can move to PyTorch APIs I'd recommend that. Feel free to follow the steps at https://pytorch.org/get-started/locally/ and hope that helps.
